# Generated by Django 2.1.3 on 2018-11-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskfield',
            name='risk_type',
        ),
        migrations.AddField(
            model_name='riskfield',
            name='enum_choices',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='risktype',
            name='risk_fields',
            field=models.ManyToManyField(to='risks.RiskField'),
        ),
        migrations.AlterField(
            model_name='riskfield',
            name='default_value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='riskfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date'), ('enum', 'enum')], default='t', max_length=100),
        ),
    ]
