# Generated by Django 2.1.3 on 2018-11-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_auto_20181125_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date'), ('enum', 'enum')], default='text', max_length=100),
        ),
    ]
