# Generated by Django 2.1.3 on 2018-11-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0003_auto_20181125_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktype',
            name='risk_name',
            field=models.CharField(max_length=100),
        ),
    ]
