# Generated by Django 2.1.3 on 2018-11-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0004_auto_20181125_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('json_body', models.TextField()),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
